# Task 1


Given the two following matrices: 

$$
A = \begin{pmatrix}
3 & 1\\ 
2 & 6
\end{pmatrix}
B = \begin{pmatrix}
-1 & 4\\ 
3 & 8
\end{pmatrix}
$$ 


In [2]:
import numpy as np
from numpy.linalg import inv

# Creating matrices
A = np.array([[ 3, 1 ],[ 2, 6]])
B = np.array([[ -1, 4 ],[ 3, 8]])


#### **(a)** $Find A^{T}$


In [11]:
A_T = A.T
print(A_T)

[[3 2]
 [1 6]]


#### **(b)** $Find B^{T}$

In [12]:
B_T = B.T
print(B_T)

[[-1  3]
 [ 4  8]]



#### **(c)** Find AB (matrix multiplication). Compare with simple multiplication
(using * instead of @ in Python). Can you see what is the difference?


In [5]:
print(A*B)

[[-3  4]
 [ 6 48]]


In [6]:
AB = A@B
print(AB)

[[ 0 20]
 [16 56]]


#### **(d)** $Find AB^{T}$


In [10]:
AB_T = AB.T
print(AB_T)

[[ 0 16]
 [20 56]]


#### **(e)** $Compare AB^{T} and A^{T}B^{T}$


In [14]:
BTAT = B_T@A_T
print(BTAT)

[[ 0 16]
 [20 56]]


#### **(f)** $Find (A^{T})^{T}$


In [15]:
AT_T = A_T.T
print(AT_T)

[[3 1]
 [2 6]]


#### **(g)** $Find AA^{T}$

In [19]:
AA_T = A@A.T
print(AA_T)

[[10 12]
 [12 40]]


# Task 2


Given 

$$
A = \begin{pmatrix}
2 & 1\\ 
3 & 2
\end{pmatrix}
B = \begin{pmatrix}
1 & 2\\ 
3 & 4
\end{pmatrix}
$$ 


#### **(a)** Find $AB$


In [22]:
A = np.array([[ 2, 1 ],[ 3, 2]])
B = np.array([[ 1, 2 ],[ 3, 4]])

In [24]:
AB = A@B
print(AB)

[[ 5  8]
 [ 9 14]]


#### **(b)** Find $BA$


In [25]:
BA = B@A
print(BA)

[[ 8  5]
 [18 11]]


# Task 3


#### **(a)** $Find A^{-1}$


In [28]:
# Inverse:
print(inv(A))

[[ 2. -1.]
 [-3.  2.]]


#### **(b)** $Find B^{-1}$


In [30]:
# Inverse:
print(inv(B))

[[-2.   1. ]
 [ 1.5 -0.5]]
