# Task 1
Given the two following matrices: 

$$
A = \begin{pmatrix}
3 & 1\\ 
2 & 6
\end{pmatrix}
B = \begin{pmatrix}
-1 & 4\\ 
3 & 8
\end{pmatrix}
$$ 


In [3]:
import numpy as np
from numpy.linalg import inv

# Creating matrices
A = np.array([[ 3, 1 ],[ 2, 6]])
B = np.array([[ -1, 4 ],[ 3, 8]])


**(a)** $Find A^{T}$

In [7]:
print(A.T)

[[3 2]
 [1 6]]


**(b)** $Find B^{T}$

In [8]:
print(B.T)

[[-1  3]
 [ 4  8]]



**(c)** Find AB (matrix multiplication). Compare with simple multiplication
(using * instead of @ in Python). Can you see what is the difference?


In [9]:
print(A*B)

[[-3  4]
 [ 6 48]]


In [11]:
print(A@B)

[[ 0 20]
 [16 56]]
